#!/usr/bin/env bash
# ─── LifeTracker Secret Generator ──────────────────────────
# Generates a secure JWT secret and DB password, then creates .env
#
# Usage:
#   chmod +x generate-secret.sh
#   ./generate-secret.sh
#
# Or pipe directly:
#   curl -fsSL https://raw.githubusercontent.com/nakulsharma97/lifetrackerr/main/generate-secret.sh | bash

set -euo pipefail

echo "🔐 Generating secrets for LifeTracker..."

# Generate a 256-bit JWT secret (Base64)
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")

# Generate a 24-byte DB password (hex)
DB_PASSWORD=$(node -e "console.log(require('crypto').randomBytes(24).toString('hex'))")

# Read .env.example and replace defaults
if [ -f .env ]; then
  echo "⚠️  .env already exists. Overwrite? [y/N]"
  read -r REPLY
  if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    echo "❌ Aborted."
    exit 1
  fi
fi

# Write .env file
cat > .env << EOF
# ─── Auto-generated by generate-secret.sh ──────────────────
# Generated: $(date -u +"%Y-%m-%d %H:%M UTC")
#
# Edit these values or re-run this script to rotate secrets.
# Docker Compose reads .env automatically.

# Database password
DB_PASSWORD=${DB_PASSWORD}

# JWT signing key (256-bit HMAC, Base64)
JWT_SECRET=${JWT_SECRET}

# SMTP / Email (optional — uncomment for password reset)
# MAIL_HOST=smtp.resend.com
# MAIL_PORT=587
# MAIL_USERNAME=resend
# MAIL_PASSWORD=re_xxxxxxxxxxxx
# MAIL_FROM=noreply@yourdomain.com

# Application base URL (used in password reset emails)
# APP_BASE_URL=https://lifetracker.yourdomain.com
EOF

echo ""
echo "✅ Done! .env created with:"
echo "   DB_PASSWORD = ${DB_PASSWORD:0:8}... (${#DB_PASSWORD} chars)"
echo "   JWT_SECRET  = ${JWT_SECRET:0:12}... (${#JWT_SECRET} chars)"
echo ""
echo "   Deploy with:  docker compose up -d"
echo "   Regenerate:   rm .env && ./generate-secret.sh"
